import { Canvas, CanvasRenderingContext2D } from 'skia-canvas';
import * as fs from 'fs';
import * as path from 'path';

export interface PlotData {
  symbol: string;
  prices: number[];
  rsi: number[];
  macd: any[];
  bb: any[];
}

export async function generatePlot(data: PlotData): Promise<Buffer> {
  const width = 1000;
  const height = 1200;
  
  console.error(`Generating informative plot for ${data.symbol}...`);
  const canvas = new Canvas(width, height);
  const ctx = canvas.getContext('2d') as unknown as CanvasRenderingContext2D;

  // Background
  ctx.fillStyle = '#121212';
  ctx.fillRect(0, 0, width, height);

  // Layout segments: Header (80px), Price (600px), RSI (220px), MACD (220px), Footer (80px)
  const headerH = 80;
  const priceH = 600;
  const rsiH = 220;
  const macdH = 220;

  drawHeader(ctx, 0, 0, width, headerH, data.symbol);
  drawPricePane(ctx, 0, headerH, width, priceH, data);
  drawRSIPane(ctx, 0, headerH + priceH, width, rsiH, data.rsi);
  drawMACDPane(ctx, 0, headerH + priceH + rsiH, width, macdH, data.macd);
  drawFooter(ctx, 0, height - 40, width, 40);

  console.error(`Converting canvas to buffer...`);
  const buffer = await canvas.toBuffer('png');
  
  const plotsDir = path.join(process.cwd(), 'plots');
  try {
    if (!fs.existsSync(plotsDir)) fs.mkdirSync(plotsDir);
    const filename = `${data.symbol.replace('/', '_').replace(':', '_')}_${Date.now()}.png`;
    const fullPath = path.join(plotsDir, filename);
    fs.writeFileSync(fullPath, buffer);
    console.error(`Plot saved to ${fullPath}`);
  } catch (err: any) {
    console.error(`Failed to save plot: ${err.message}`);
  }

  return buffer;
}

function drawHeader(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, symbol: string) {
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 32px sans-serif';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'middle';
  ctx.fillText(`${symbol} Technical Analysis`, x + 40, y + h / 2);
  
  ctx.font = '16px sans-serif';
  ctx.fillStyle = '#888888';
  ctx.textAlign = 'right';
  ctx.fillText(new Date().toLocaleString(), w - 40, y + h / 2);
}

function drawFooter(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number) {
  ctx.fillStyle = '#444444';
  ctx.font = '12px sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('Generated by Financial Indicators MCP Server', w / 2, y + 20);
}

function drawPricePane(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, data: PlotData) {
  const marginL = 80;
  const marginR = 80;
  const marginT = 40;
  const marginB = 40;
  const chartW = w - marginL - marginR;
  const chartH = h - marginT - marginB;

  // Grid and Box
  ctx.strokeStyle = '#333333';
  ctx.strokeRect(x + marginL, y + marginT, chartW, chartH);

  if (data.prices.length < 2) return;

  const minPrice = Math.min(...data.prices, ...(data.bb.map(b => b.lower).filter(v => v !== undefined)));
  const maxPrice = Math.max(...data.prices, ...(data.bb.map(b => b.upper).filter(v => v !== undefined)));
  const range = (maxPrice - minPrice) * 1.1 || 1;
  const base = minPrice - (maxPrice - minPrice) * 0.05;

  // Horizontal Grid Lines & Price Labels
  ctx.textAlign = 'right';
  ctx.font = '12px sans-serif';
  for (let i = 0; i <= 5; i++) {
    const val = base + (range * i) / 5;
    const gy = y + marginT + chartH - (i / 5) * chartH;
    ctx.beginPath();
    ctx.moveTo(x + marginL, gy);
    ctx.lineTo(x + marginL + chartW, gy);
    ctx.stroke();
    ctx.fillStyle = '#888888';
    ctx.fillText(val.toLocaleString(undefined, { maximumFractionDigits: 2 }), x + marginL - 10, gy + 5);
  }

  // Legend
  ctx.textAlign = 'left';
  ctx.fillStyle = '#00ff00'; ctx.fillText('■ Price', x + marginL + 10, y + marginT - 15);
  ctx.fillStyle = '#5555ff'; ctx.fillText('■ Bollinger Bands', x + marginL + 100, y + marginT - 15);

  // Price Line
  ctx.beginPath();
  ctx.strokeStyle = '#00ff00';
  ctx.lineWidth = 2;
  for (let i = 0; i < data.prices.length; i++) {
    const px = x + marginL + (i / (data.prices.length - 1)) * chartW;
    const py = y + marginT + chartH - ((data.prices[i] - base) / range) * chartH;
    if (i === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  }
  ctx.stroke();

  // Bollinger Bands
  if (data.bb.length > 0) {
    ctx.lineWidth = 1;
    ctx.strokeStyle = '#5555ff';
    ctx.setLineDash([5, 5]);
    
    // Upper
    ctx.beginPath();
    for (let i = 0; i < data.bb.length; i++) {
      const idx = data.prices.length - data.bb.length + i;
      const px = x + marginL + (idx / (data.prices.length - 1)) * chartW;
      const py = y + marginT + chartH - ((data.bb[i].upper - base) / range) * chartH;
      if (i === 0) ctx.moveTo(px, py);
      else ctx.lineTo(px, py);
    }
    ctx.stroke();

    // Lower
    ctx.beginPath();
    for (let i = 0; i < data.bb.length; i++) {
      const idx = data.prices.length - data.bb.length + i;
      const px = x + marginL + (idx / (data.prices.length - 1)) * chartW;
      const py = y + marginT + chartH - ((data.bb[i].lower - base) / range) * chartH;
      if (i === 0) ctx.moveTo(px, py);
      else ctx.lineTo(px, py);
    }
    ctx.stroke();
    ctx.setLineDash([]);
  }
}

function drawRSIPane(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, rsi: number[]) {
  const marginL = 80;
  const marginR = 80;
  const marginT = 40;
  const marginB = 30;
  const chartW = w - marginL - marginR;
  const chartH = h - marginT - marginB;

  ctx.strokeStyle = '#333333';
  ctx.strokeRect(x + marginL, y + marginT, chartW, chartH);

  // Labels
  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 14px sans-serif';
  ctx.textAlign = 'left';
  ctx.fillText('RSI (14)', x + marginL, y + marginT - 10);

  // Scale labels
  ctx.font = '12px sans-serif';
  ctx.fillStyle = '#888888';
  ctx.textAlign = 'right';
  [0, 30, 50, 70, 100].forEach(val => {
    const ly = y + marginT + chartH - (val / 100) * chartH;
    ctx.fillText(val.toString(), x + marginL - 10, ly + 5);
    ctx.beginPath();
    ctx.moveTo(x + marginL, ly);
    ctx.lineTo(x + marginL + chartW, ly);
    ctx.strokeStyle = val === 30 || val === 70 ? '#552222' : '#222222';
    ctx.stroke();
  });

  if (rsi.length < 2) return;

  ctx.beginPath();
  ctx.strokeStyle = '#ff00ff';
  ctx.lineWidth = 2;
  for (let i = 0; i < rsi.length; i++) {
    const px = x + marginL + (i / (rsi.length - 1)) * chartW;
    const py = y + marginT + chartH - (rsi[i] / 100) * chartH;
    if (i === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  }
  ctx.stroke();
}

function drawMACDPane(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, macd: any[]) {
  const marginL = 80;
  const marginR = 80;
  const marginT = 40;
  const marginB = 30;
  const chartW = w - marginL - marginR;
  const chartH = h - marginT - marginB;

  ctx.strokeStyle = '#333333';
  ctx.strokeRect(x + marginL, y + marginT, chartW, chartH);

  ctx.fillStyle = '#ffffff';
  ctx.font = 'bold 14px sans-serif';
  ctx.textAlign = 'left';
  ctx.fillText('MACD (12, 26, 9)', x + marginL, y + marginT - 10);

  if (macd.length < 2) return;
  const validMacd = macd.filter(m => m.MACD !== undefined);
  if (validMacd.length < 2) return;

  const vals = validMacd.map(m => [m.MACD, m.signal, m.histogram]).flat();
  const min = Math.min(...vals);
  const max = Math.max(...vals);
  const range = (max - min) * 1.1 || 1;
  const base = min - (max - min) * 0.05;

  // Scale
  ctx.font = '12px sans-serif';
  ctx.fillStyle = '#888888';
  ctx.textAlign = 'right';
  for (let i = 0; i <= 4; i++) {
    const val = base + (range * i) / 4;
    const ly = y + marginT + chartH - (i / 4) * chartH;
    ctx.fillText(val.toFixed(0), x + marginL - 10, ly + 5);
    ctx.beginPath();
    ctx.moveTo(x + marginL, ly);
    ctx.lineTo(x + marginL + chartW, ly);
    ctx.strokeStyle = '#222222';
    ctx.stroke();
  }

  // Legend
  ctx.textAlign = 'left';
  ctx.fillStyle = '#0000ff'; ctx.fillText('■ MACD', x + marginL + 120, y + marginT - 10);
  ctx.fillStyle = '#ffaa00'; ctx.fillText('■ Signal', x + marginL + 200, y + marginT - 10);

  // Histogram
  for (let i = 0; i < validMacd.length; i++) {
    const m = validMacd[i];
    const px = x + marginL + (i / (validMacd.length - 1)) * chartW;
    const zeroY = y + marginT + chartH - ((0 - base) / range) * chartH;
    const py = y + marginT + chartH - ((m.histogram - base) / range) * chartH;
    ctx.fillStyle = m.histogram >= 0 ? 'rgba(0, 200, 0, 0.5)' : 'rgba(200, 0, 0, 0.5)';
    const barW = Math.max(1, chartW / validMacd.length - 2);
    ctx.fillRect(px - barW / 2, zeroY, barW, py - zeroY);
  }

  // MACD Line
  ctx.beginPath();
  ctx.strokeStyle = '#0000ff';
  ctx.lineWidth = 1.5;
  for (let i = 0; i < validMacd.length; i++) {
    const px = x + marginL + (i / (validMacd.length - 1)) * chartW;
    const py = y + marginT + chartH - ((validMacd[i].MACD - base) / range) * chartH;
    if (i === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  }
  ctx.stroke();

  // Signal Line
  ctx.beginPath();
  ctx.strokeStyle = '#ffaa00';
  ctx.lineWidth = 1.5;
  for (let i = 0; i < validMacd.length; i++) {
    const px = x + marginL + (i / (validMacd.length - 1)) * chartW;
    const py = y + marginT + chartH - ((validMacd[i].signal - base) / range) * chartH;
    if (i === 0) ctx.moveTo(px, py);
    else ctx.lineTo(px, py);
  }
  ctx.stroke();
}
